### ISSUE TITLE
Grove LCD RGB Backlight example code doesn't seem to work

### ISSUE THREAD

**Issue by robotmechanic** [Seeed-Studio/Sketchbook_Starter_Kit_for_Arduino#2]
Even when switching to 5v on the backpack, the display shows only a row of black squares when used with the Arduino Uno. The sample code for the rest of the modules seem to work fine.

Any advice or suggestions would be greatly appreciated.

**Comment by ericjnorman** [comment]
Was able to get text to display by connecting the power line to the VCC header which puts out 5V. The I2C connector puts out 3.3V.
![img_9263](https://cloud.githubusercontent.com/assets/7156025/26533659/0827ab7c-43d1-11e7-9cc9-8442a62a1824.JPG)

**Comment by baorepo** [comment]
good job
