### ISSUE TITLE
Grove LCD RGB Backlight example code doesn't to work rgb_lcd.h

### ISSUE THREAD

**Issue by PeerAmpere** [Seeed-Studio/Sketchbook_Starter_Kit_for_Arduino#6]
Uploading a program, I get the error that he can not find a program or directory with that name. But it is in the Example directory. Tried moving it, but no result.

**Comment by oz-** [comment]
Same thing here on a Mac with a specific Arduino sketches directory.

**Comment by baorepo** [comment]
any updates
